server.address=0.0.0.0
# server.port=8080  # Cambiado de 8080 a 8443 para HTTPS

spring.application.name=backend-impulse

# Configuración para MySQL
spring.datasource.url=jdbc:mysql://db-impulse-1d.ck7aeuk6sobk.us-east-1.rds.amazonaws.com:3306/db-impulse-1d
spring.datasource.username=admin
spring.datasource.password=12345678

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Configuración del certificado SSL para habilitar HTTPS
server.ssl.key-store=file:keystore.p12
server.ssl.key-store-password=12345678
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=impulse-cert
server.port=8443

# Configuración de credenciales del bucket donde se suben las imágenes
aws.accessKey=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.s3.region=${AWS_REGION}
aws.s3.bucketName=${BUCKET_NAME}

# Configuración de H2 (comentada ya que no se usará una base local por ser temporal)
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# spring.datasource.username=sa
# spring.datasource.password=password
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.url=jdbc:h2:mem:impulse_db
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=create-drop
